name: Check

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup component add clippy

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust
          shared-key: ubuntu-latest@debug

      - name: Clippy
        run: cargo clippy --all

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        run: |
          rustup toolchain install nightly --profile minimal
          rustup component add rustfmt --toolchain nightly

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: rust
          shared-key: ubuntu-latest@debug

      - name: Rustfmt
        run: cargo +nightly fmt --all -- --check
